apiVersion: v1
type: Opaque
metadata:
  name: orchestra-secrets-source
  namespace: openunison
data:
  K8S_DB_SECRET: aW0gYSBzZWNyZXQ=
  SMTP_PASSWORD: ""
  OU_JDBC_PASSWORD: c3RhcnR0MTIz
  unisonKeystorePassword: aW0gYSBzZWNyZXQ=
kind: Secret